version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password123
    volumes:
      - db-data:/var/lib/postgresql/data
  testdb:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password123
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
